name: checkkhodam
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  image_picker: ^0.8.5+3
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.4
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/Ellipse 61.png
    - assets/images/Ellipse 62.png
    - assets/images/Ellipse 63.png
    - assets/images/CHECKHODAM.png
    - assets/images/CHECKHODAM_1.png
    - assets/images/Rectangle 354.png
    - assets/images/Ellipse 60.png

  fonts:
    - family: DEATH_FONT
      fonts:
        - asset: assets/fonts/DEATH_FONT.TTF
        - asset: assets/fonts/kannada-sangam-mn.ttf
        - asset: assets/fonts/micross.ttf   

