name: checkkhodam
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  image_picker: ^0.8.5+3
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.4
  path: ^1.9.0
  http: ^1.2.2
  image: ^3.3.0
  share_plus: ^10.1.2
  screenshot: ^3.0.0
  dio: ^5.7.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/bg_quiz_odd.png
    - assets/images/bg_quiz_even.png
    - assets/images/bg_asset_quiz0.png
    - assets/images/Ellipse 60.png
    - assets/images/Ellipse 61.png
    - assets/images/Ellipse 62.png
    - assets/images/Ellipse 63.png
    - assets/images/Ellipse 70.png
    - assets/images/Ellipse 71.png
    - assets/images/CHECKHODAM.png
    - assets/images/CHECKHODAM_1.png
    - assets/images/Rectangle 353.png
    - assets/images/Rectangle 354.png
    - assets/images/Group 45.png
    - assets/images/Group 43.png
    - assets/images/Group 47.png
    - assets/images/Ellipse 65.png
    - assets/images/Ellipse 67.png
    - assets/images/Ellipse 69.png
    - assets/images/Final State.png
    - assets/images/Search More.png
    - assets/images/Icon.png
    - assets/images/Rotate Camera.png
    - assets/images/ic_process.png
    - assets/images/Rectangle 360.png
    - assets/images/Save.png

  fonts:
    - family: DEATH_FONT
      fonts:
        - asset: assets/fonts/DEATH_FONT.TTF
        - asset: assets/fonts/kannada-sangam-mn.ttf

    - family: boxpot
      fonts:
        - asset: assets/fonts/boxpot1.ttf
        
    - family: micross
      fonts:
        - asset: assets/fonts/micross.ttf 
